declare @buscar varchar(50)
SET @buscar = 'cartera'

 

SELECT 
ROUTINE_NAME
,ROUTINE_DEFINITION
FROM 
INFORMATION_SCHEMA.ROUTINES
WHERE 
ROUTINE_NAME LIKE '%' + @buscar + '%'
AND ROUTINE_TYPE ='PROCEDURE'
ORDER BY
ROUTINE_NAME